name: Publish Package
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: Install packages
        run: yarn install
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
